-- ==============================================================================
-- Supabase Schema: Client Inquiries & Presentation Leads
-- Kumari Sneha — Presentation Design Portfolio
-- ==============================================================================

-- 1. Create table for client inquiries
create table if not exists public.portfolio_inquiries (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  email text not null,
  company text,
  project_type text default 'Investor Pitch Deck',
  timeline text default '2-3 weeks',
  message text not null,
  status text default 'new' -- 'new', 'in_discussion', 'booked', 'archived'
);

-- 2. Enable Row Level Security (RLS) for protection
alter table public.portfolio_inquiries enable row level security;

-- 3. Policy: Allow prospective clients / visitors to insert inquiries
create policy "Allow anonymous submissions"
  on public.portfolio_inquiries
  for insert
  with check (true);

-- 4. Policy: Allow authenticated dashboard users to view inquiries
create policy "Allow authenticated user access"
  on public.portfolio_inquiries
  for select
  using (auth.role() = 'authenticated');

-- 5. Rapid sorting index
create index if not exists idx_inquiries_created_at on public.portfolio_inquiries(created_at desc);
